### ISSUE TITLE
refactoring and separating

### ISSUE THREAD

**Issue by tunnckoCore** [jonschlinkert/fs-utils#2]
Hi, hi. @jonschlinkert @doowb 
I think it can be rewritten and can significantly be reduce size amount if we update/refactor also the chain [`write`](https://github.com/jonschlinkert/write) -> [`write-yaml`](https://github.com/jonschlinkert/write-yaml) -> [`read-yaml`](https://github.com/jonschlinkert/read-yaml) -> [`read-data`](https://github.com/jonschlinkert/read-data) -> [`read-file`](https://github.com/jonschlinkert/read-file) and their dependants. Because you already create these modules but you dont use them in each other.. I think we can do it before its too late - knowing that all of these modules have ~ 5 ~ 40+ dependants (fs-utils have 41).

This make me thinking for such deps structure

- fs-utils deps:
  + data-utils (to be created, name is free, btw) deps:
    - read-data deps:
      + read-file (need refactor, comments) also can use `strip-bom`
	  + read-yaml
    - write-data (to be created, name is free, btw) deps:
      + write-file
      + write-yaml - bad.. not follows convention `fn` / `fnSync`, support only `fn` which is sync
  + [sindresorhus/strip-bom](https://github.com/sindresorhus/strip-bom)
  + [is-directory](https://github.com/jonschlinkert/is-directory)
  + [del](https://github.com/sindresorhus/del) / [delete](https://github.com/jonschlinkert/delete) - really, I cant realize whats the difference, yet, so months. Yea delete is without `globby`, but here you use `globby` and `async` in `.del` / `.deleteAsync` / `deleteSync`
  + also `.rmdir` will be just `del`, with some checks to  guarantee `fp` is dir?
  + [is-path-cwd](https://github.com/sindresorhus/is-path-cwd)
  + [is-path-in-cwd](https://github.com/sindresorhus/is-path-in-cwd)

[each-async](https://github.com/sindresorhus/each-async) / [catchy](https://github.com/tunnckoCore/catchy) (my promise-like async flow) / [run-parallel](https://github.com/feross/run-parallel) / [run-waterfall](https://github.com/feross/run-waterfall) instead of whole `async`

At all.. normalize all them to `fn` / `fnSync`, to could support promises, or why not `fnPromise`?
Support option to plug-in promise library of choice? For that we can use that is in my mind at the moment - `promise(s)-normalize`/`normalize-promise(s)` - that will normalize the promise libraries; like [jstransformers](https://github.com/jstransformers) by @ForbesLindesay, do normalize transformers/engines.

**And the final result would be awesome ... You can imagine how shorter and better will be for the future**

Its easy to just start to clone and republish these packages with another names, but there's no logic. We can invest some work to make them better, no matter of breaks - I think `semver` is for this? I understand that the biggest problem will be this, won't the hard work that we invest.

I can show the final `fs-utils` result if you want, then can invest some time to clone repos and make all this work for demo, of course with tests.

#### Very thanks! :)

**Comment by jonschlinkert** [comment]
closing based on age
