### ISSUE TITLE
Cannot find module './utils'

### ISSUE THREAD

**Issue by r0mant** [jonschlinkert/fs-utils#4]
Hey @jonschlinkert,

Looks like this commit, https://github.com/jonschlinkert/fs-utils/commit/0a265930c93a9427f2fd43f9125d7de807b15e67, broke some stuff because we started getting an error "cannot find module ./utils" during our deployment.

I see that `index.js` requires `utils` but I don't see `utils.js` after `npm i fs-utils`:

```
$ ll node_modules/fs-utils/
total 44K
-rw-rw-r-- 1 mg mg  20K Oct 31 18:58 index.js
-rw-rw-r-- 1 mg mg 1.1K Oct 31 18:43 LICENSE
drwxrwxr-x 4 mg mg 4.0K Nov  3 01:23 node_modules
-rw-rw-r-- 1 mg mg 2.7K Nov  3 01:23 package.json
-rw-rw-r-- 1 mg mg 8.6K Oct 31 18:45 readme.md
```

**Comment by jonschlinkert** [comment]
Really sorry about that. should be fixed. thanks for letting me know.

**Comment by r0mant** [comment]
Yep, it works now. Thanks for the quick help @jonschlinkert!

**Comment by jonschlinkert** [comment]
Anytime! Sorry for the issue!
